In [1]:
import numpy as np
import sympy as sp

In [2]:
#Q2.
np.random.seed(39)
A=np.random.randint(0,10,(5,5))
A

array([[9, 9, 9, 0, 4],
       [6, 3, 0, 4, 8],
       [1, 4, 9, 0, 4],
       [4, 4, 9, 6, 5],
       [7, 8, 8, 8, 7]])

In [3]:
A=np.array([[9, 9, 9, 0, 4],[6, 3, 0, 4, 8],[1, 4, 9, 0, 4],[4, 4, 9, 6, 5],[7, 8, 8, 8, 7]])
A[0]=A[0]/9
A

array([[1, 1, 1, 0, 0],
       [6, 3, 0, 4, 8],
       [1, 4, 9, 0, 4],
       [4, 4, 9, 6, 5],
       [7, 8, 8, 8, 7]])

In [4]:
A[1]=A[1]-6*A[0]
A[2]=A[2]-A[0]
A[3]=A[3]-4*A[0]
A[4]=A[4]-7*A[0]
A

array([[ 1,  1,  1,  0,  0],
       [ 0, -3, -6,  4,  8],
       [ 0,  3,  8,  0,  4],
       [ 0,  0,  5,  6,  5],
       [ 0,  1,  1,  8,  7]])

In [5]:
A[1]=-A[1]/3
A

array([[ 1,  1,  1,  0,  0],
       [ 0,  1,  2, -1, -2],
       [ 0,  3,  8,  0,  4],
       [ 0,  0,  5,  6,  5],
       [ 0,  1,  1,  8,  7]])

In [6]:
A[2]=A[2]-3*A[1]
A[4]=A[4]-A[1]
A

array([[ 1,  1,  1,  0,  0],
       [ 0,  1,  2, -1, -2],
       [ 0,  0,  2,  3, 10],
       [ 0,  0,  5,  6,  5],
       [ 0,  0, -1,  9,  9]])

In [7]:
A[2]=A[2]/2
A

array([[ 1,  1,  1,  0,  0],
       [ 0,  1,  2, -1, -2],
       [ 0,  0,  1,  1,  5],
       [ 0,  0,  5,  6,  5],
       [ 0,  0, -1,  9,  9]])

In [8]:
A[3]=A[3]-5*A[2]
A[4]=A[4]+A[2]
A

array([[  1,   1,   1,   0,   0],
       [  0,   1,   2,  -1,  -2],
       [  0,   0,   1,   1,   5],
       [  0,   0,   0,   1, -20],
       [  0,   0,   0,  10,  14]])

In [9]:
A[4]=A[4]-10*A[3]
A

array([[  1,   1,   1,   0,   0],
       [  0,   1,   2,  -1,  -2],
       [  0,   0,   1,   1,   5],
       [  0,   0,   0,   1, -20],
       [  0,   0,   0,   0, 214]])

In [10]:
A[4]=A[4]/214
A

array([[  1,   1,   1,   0,   0],
       [  0,   1,   2,  -1,  -2],
       [  0,   0,   1,   1,   5],
       [  0,   0,   0,   1, -20],
       [  0,   0,   0,   0,   1]])